backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "kozlemenyek"
    label: "Közlemények"
    folder: "_posts/kozlemenyek"
    create: true
    fields:
      - {label: "Cím", name: "title", widget: "string"}
      - {label: "Dátum (ÉÉÉÉ-HH-NN)", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Tartalom", name: "body", widget: "markdown"}

  - name: "esemenyek"
    label: "Események"
    folder: "_posts/esemenyek"
    create: true
    fields:
      - {label: "Esemény neve", name: "title", widget: "string"}
      - {label: "Dátum (ÉÉÉÉ-HH-NN)", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Pontos időpont (pl. 17:00)", name: "idopont", widget: "string", required: false}
      - {label: "Helyszín", name: "location", widget: "string", required: false}
      - {label: "Leírás", name: "body", widget: "markdown"}
